
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.vishal.widgetstore.services;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.2.0
 * 2017-10-12T22:48:20.356-04:00
 * Generated source version: 3.2.0
 * 
 */

@javax.jws.WebService(
                      serviceName = "OrderEndpointService",
                      portName = "OrderBinding",
                      targetNamespace = "com.vishal.partdepot",
                      wsdlLocation = "file:/home/admin/workspace/WidgetStore/src/main/resources/wsdl/order.wsdl",
                      endpointInterface = "com.vishal.widgetstore.services.OrderEndpoint")
                      
public class OrderBindingImpl implements OrderEndpoint {

    private static final Logger LOG = Logger.getLogger(OrderBindingImpl.class.getName());

    /* (non-Javadoc)
     * @see com.vishal.widgetstore.services.OrderEndpoint#placeOrder(com.vishal.widgetstore.services.Order order)*
     */
    public java.lang.String placeOrder(com.vishal.widgetstore.services.Order order) { 
        LOG.info("Executing operation placeOrder");
        System.out.println(order);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
