package com.vishal.widgetstore.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.0
 * 2017-10-12T22:48:20.394-04:00
 * Generated source version: 3.2.0
 * 
 */
@WebServiceClient(name = "OrderEndpointService", 
                  wsdlLocation = "file:/home/admin/workspace/WidgetStore/src/main/resources/wsdl/order.wsdl",
                  targetNamespace = "com.vishal.partdepot") 
public class OrderEndpointService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("com.vishal.partdepot", "OrderEndpointService");
    public final static QName OrderBinding = new QName("com.vishal.partdepot", "OrderBinding");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/admin/workspace/WidgetStore/src/main/resources/wsdl/order.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OrderEndpointService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/admin/workspace/WidgetStore/src/main/resources/wsdl/order.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public OrderEndpointService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OrderEndpointService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrderEndpointService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public OrderEndpointService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public OrderEndpointService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public OrderEndpointService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns OrderEndpoint
     */
    @WebEndpoint(name = "OrderBinding")
    public OrderEndpoint getOrderBinding() {
        return super.getPort(OrderBinding, OrderEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrderEndpoint
     */
    @WebEndpoint(name = "OrderBinding")
    public OrderEndpoint getOrderBinding(WebServiceFeature... features) {
        return super.getPort(OrderBinding, OrderEndpoint.class, features);
    }

}
